# Etapa 1: Builder (instala dependencias)
FROM python:3.11-alpine AS builder

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Etapa 2: Imagen final (ligera)
FROM python:3.11-alpine

WORKDIR /app
COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY app.py excel_utils.py .
COPY templates/ templates/

RUN adduser -D appuser && chown -R appuser /app
USER appuser

EXPOSE 5000
CMD ["python", "app.py"]